### PR TITLE
Jsx3

### PR DESCRIPTION
**Pull request by JakubMarkiewicz**
Not everything is ready but i think we can move it forward as most components are fine.

### CODE REVIEW

**Comment by Enalmada** [comment]
Awesome!  I will give it a go in my test environment here: https://github.com/Enalmada/next-reason-boilerplate in a bit.  Let me know if you would benefit from more direct access to the repo so you can just push things you are certain need to be done without friction.

**Comment by JakubMarkiewicz** [comment]
Thanks, I surely want to add every component to `./examples` since i'm not completely sure which components need more work. For these or for small fixes direct access would be lovely. For bigger changes i'd prefer doing PRs after we merge this, i'm lacking a lot of knowledge in BS/Reason at the moment. 
If you need anything related to this jsx3 PR you can hit me on discord.

**Comment by Enalmada** [comment]
FYI I pushed a fix for `childre:`  in Layout and Menu and added title to SubMenu.  I also gave you collaborator access.  

jsx3 looks like it really simplifies everything!  I tried updating my example project to use the jsx3 version of bs-ant-design and got a bunch of errors.  I guess to be able to import jsx3 bindings,  I need to enable jsx3 on the primary project that imports it....which I guess requires converting all bindings that project importes to jsx3?  

I have a bunch of bindings my test project I use to verify bs-ant-design changes...I will need to carve out some time to learn how to update them so I can get to the point where I can verify this pull request: 
https://github.com/Enalmada/bs-ant-design-mobile
https://github.com/Enalmada/bs-next-seo
https://github.com/Enalmada/bs-next
https://github.com/Enalmada/bs-react-iframe
https://github.com/Enalmada/bs-fontawesome  

Just thinking aloud...is it possible to support jsx2 for old projects and jsx3 for new projects at the same time with the same bindings code?  Is that what you are trying to do here? https://github.com/apollographql/reason-apollo/pull/190/files

**Comment by JakubMarkiewicz** [comment]
Yes if you want to use jsx3 bindings you need to set root project to jsx3 or use ` ReasonReactCompat.wrapReactForReasonReact ` but you will need to do that to every component that you need to use. I'm still using jsx2 version in job because of other packages that uses jsx2. 
The pr to reason-apollo is just another way of doing the same thing that i did in this PR, but this way i can tell component that a children is actually a function and pass props to it.
I did try this approach here but it didn't fit because default props were overridden by ` undefined ` if nothing was passed to component. 
By the way, i found this today https://github.com/zpnester/bs-antd/. Didn't test it but i see that it's being actively developed.

**Comment by Enalmada** [comment]
Ah thanks for the explanation and confirmation about migration path!  Ok, so I will update all the bindings under my control with a major version update and readme note that jsx3 migration required.  I don't mind a clean break.  reason-apollo I think is the only binding I care about that isn't under my control.  Did you sign your Meteor Contributor Agreement?  It looks like your pull request is waiting on that.  Hopefully when that is merged in we can ask him to push some sort of alpha release?

OH MY that is interesting someone is doing a bs-antd at almost the same time.  The original bs-antd is no longer being maintained and sadly I don't think there is any link from it to bs-ant-design.  I am not at all surprised.  It would be better if there was only one "bs ant design" so we should figure out the right way to join forces.

**Comment by JakubMarkiewicz** [comment]
I indeed did sign MCA, we have to wait i guess.
If you'r not using ` <ApolloConsumer> ` and want jsx3 you can use reason-apollo@alpha, it works well for me.
Yea I agree that one package is the best way to go. I notice some differences right off the bat between this PR and mentioned package but didn't look deeply into it.

**Comment by Enalmada** [comment]
Oh there is a reason-apollo@alpha?!  Thanks I will try that!

I guess take a look and the differences with bs-antd and think about best way to reconcile while I get the rest of my modules upgraded to jsx3.  Since bs-ant-design project has community around it I think the best course of action would be for one of us to ask for ownership of git and npm and then share that with the rest of us.  I have never got npm access from someone but I think it is possible....I would rather maintain bs-ant-design than bs-ant-design-alt long term because it is a good name....bs-antd not bad either though.

**Comment by Enalmada** [comment]
Published under `bs-ant-design-alt@2.0.0-alpha.1` so that people who want to get going on jsx have something to use.  @JakubMarkiewicz....thank you so much for taking the time to do this for the community.  Let me know your npm username if you want npm publish access.

**Comment by JakubMarkiewicz** [comment]
I agree that bs-antd-design is probably the best name, i see that you asked for permission so we'r waiting.
Meanwhile we can develop here until stable version can be released.
My npm username is `jakubmarkiewicz` https://www.npmjs.com/~jakubmarkiewicz

**Pull request merged**
